name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # Use cache only if a pnpm lockfile exists
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Ensure lockfile
        run: |
          if [ ! -f pnpm-lock.yaml ]; then pnpm install --lockfile-only; fi

      - name: Get pnpm store path
        run: echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      # Lint step disabled (no root lint script yet)
      # - name: Lint
      #   run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Run Playwright tests
        run: pnpm exec playwright test
