name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # Use cache only if a pnpm lockfile exists
      - name: Setup Node (cached)
        if: ${{ hashFiles('pnpm-lock.yaml') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup Node (no cache)
        if: ${{ hashFiles('pnpm-lock.yaml') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      # Lint step disabled (no root lint script yet)
      # - name: Lint
      #   run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Run Playwright tests
        run: pnpm exec playwright test
